### PR TITLE
Modernize 0.10.2

### PR DESCRIPTION
**Pull request by sdvillal**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

This simple PR:
- Modernizes the v0.10.2 package building against python 3.9 (note that 0.11 seems an unreleased version)
- Fixes the download URL (otherwise checksum fails)
- Disables windows builds (pytorch is not build for win in CF, using pytorch-cpu might be an option)

This compiles just fine now (see it in my [personal channel](https://anaconda.org/sdvillal/fairseq), ```sdvillal::fairseq```). It would potentially alleviate the pain of a few users ([1](https://github.com/pytorch/fairseq/issues/3535) and [2](https://github.com/oxpig/AbLang/issues/1)), or at least give some hints as of why #16 and #14 fail.

### CODE REVIEW

**Comment by maclandrol** [comment]
@sdvillal Any chances of this getting merged soon ?

**Comment by sdvillal** [comment]
@maclandrol I do not have rights.

**Comment by hadim** [comment]
@conda-forge/core could you merge this PR or give the correct permissions to @sdvillal to do it please?

**Comment by hadim** [comment]
Thank you @hmaarrfk

**Pull request merged**
